exporter_host: 0.0.0.0
exporter_port: 9127

pgbouncers:
  - dsn: "postgres://postgres:zRqdRIzBZCDEpmSEJSDyCjCijGIqGmus@shortline.proxy.rlwy.net:48035/railway?sslmode=disable"
    labels:
      alias: "pgbouncer_shortline"

  - dsn: "postgres://postgres:zRqdRIzBZCDEpmSEJSDyCjCijGIqGmus@mainline.proxy.rlwy.net:30214/railway?sslmode=disable"
    labels:
      alias: "pgbouncer_mainline"

  - dsn: "postgres://postgres:zRqdRIzBZCDEpmSEJSDyCjCijGIqGmus@nozomi.proxy.rlwy.net:48720/railway?sslmode=disable"
    labels:
      alias: "pgbouncer_nozomi"
