exporter_host: 0.0.0.0
exporter_port: 9127

pgbouncers:
  - dsn: "postgres://postgres:zRqdRIzBZCDEpmSEJSDyCjCijGIqGmus@shortline.proxy.rlwy.net:48035/railway?sslmode=disable"
    labels:
      instance: "shortline"
      group: "pgbouncer-1"

  - dsn: "postgres://postgres:zRqdRIzBZCDEpmSEJSDyCjCijGIqGmus@mainline.proxy.rlwy.net:30214/railway?sslmode=disable"
    labels:
      instance: "mainline"
      group: "pgbouncer-2"

  - dsn: "postgres://postgres:zRqdRIzBZCDEpmSEJSDyCjCijGIqGmus@nozomi.proxy.rlwy.net:48720/railway?sslmode=disable"
    labels:
      instance: "nozomi"
      group: "pgbouncer-3"
